"""add financial_facts table

Revision ID: 49a7bdcbee21
Revises: d725e8ca3204
Create Date: 2026-06-21 20:18:40.658720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a7bdcbee21'
down_revision: Union[str, Sequence[str], None] = 'd725e8ca3204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=60), nullable=False),
    sa.Column('xbrl_tag', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=10), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ff_company_metric_period', 'financial_facts', ['company_id', 'metric_name', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ff_company_metric_period', table_name='financial_facts')
    op.drop_table('financial_facts')
    # ### end Alembic commands ###
